export const DaySnow = () => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img">
    <path
      d="M17.7 32a10 10 0 1 1 13.5-13M22 3v4M6 23H2M8 9l3 3m25-3l-3 3M11 34l-3 3"
      fill="none"
      stroke="currentColor"
      stroke-miterlimit="10"
      stroke-width="2"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></path>
    <path
      d="M50 25a13 13 0 0 0-25 4.1h-1a8 8 0 1 0 0 16h26a10 10 0 0 0 0-20z"
      fill="none"
      stroke="currentColor"
      stroke-miterlimit="10"
      stroke-width="2"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></path>
    <circle
      cx="24"
      cy="50"
      r="1"
      fill="none"
      stroke="currentColor"
      stroke-miterlimit="10"
      stroke-width="2"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></circle>
    <circle
      cx="40"
      cy="50"
      r="1"
      fill="none"
      stroke="currentColor"
      stroke-miterlimit="10"
      stroke-width="2"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></circle>
    <circle
      cx="50"
      cy="52"
      r="1"
      fill="none"
      stroke="currentColor"
      stroke-miterlimit="10"
      stroke-width="2"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></circle>
    <circle
      cx="30"
      cy="54"
      r="1"
      fill="none"
      stroke="currentColor"
      stroke-miterlimit="10"
      stroke-width="2"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></circle>
    <circle
      cx="22"
      cy="58"
      r="1"
      fill="none"
      stroke="currentColor"
      stroke-miterlimit="10"
      stroke-width="2"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></circle>
    <circle
      cx="38"
      cy="58"
      r="1"
      fill="none"
      stroke="currentColor"
      stroke-miterlimit="10"
      stroke-width="2"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></circle>
    <circle
      cx="48"
      cy="60"
      r="1"
      fill="none"
      stroke="currentColor"
      stroke-miterlimit="10"
      stroke-width="2"
      stroke-linejoin="round"
      stroke-linecap="round"
    ></circle>
  </svg>
);
